For review: Nickname owner endpoint
roaminro/koinos-rest pull request #16
Opened 2023-11-07 02:00 UTC by gtandes

2023-11-07 05:42 UTC, roaminro requested changes

2023-11-07 05:42 UTC, roaminro commented on app/api/nicknames/[nickname]/address/route.ts
> + * /api/nicknames/{nickname}/address:
let's use `{account}` for the parameter to keep it consistant with the `kap` endpoints.
This means that the route also need to be updated (the folder name of the route)

2023-11-07 05:42 UTC, roaminro commented on app/api/nicknames/[nickname]/address/route.ts
> +        ownerAddress
To keep it consistant with the `kap` route, let's use `address` as the returned object key

2023-11-07 05:42 UTC, roaminro commented on services/nicknames.ts
> +export async function getNicknameOwner(name: string): Promise<Nickname | undefined> {
The return type is incorrect, the result of `owner_of` if of type `{ address: string }`

2023-11-07 06:14 UTC, gtandes commented on app/api/nicknames/[nickname]/address/route.ts
> +        ownerAddress
done

2023-11-07 06:14 UTC, gtandes commented on app/api/nicknames/[nickname]/address/route.ts
> + * /api/nicknames/{nickname}/address:
done

2023-11-07 06:17 UTC, gtandes commented on services/nicknames.ts
> +export async function getNicknameOwner(name: string): Promise<Nickname | undefined> {
May I know where I should make the changes?

the return type of owner_of here is already a string:

  const { result } = await contract.functions.owner_of<{ token_id: string }>({
    token_id: stringToHex
  })
  
  and
  
  so is type Nickname = { token_id: string }

2023-11-07 20:48 UTC, roaminro requested changes

2023-11-07 20:48 UTC, roaminro commented on services/nicknames.ts
> +  return result
need to return `result.address` here otherwise you get an object when calling `getNicknameOwner` which returns an object when calling the api:

current result:
```json
{
  "address": {
    "account": "1MdqwaSBy6rbasPJ9vmg2pZFJSVZ29GFpZ"
  }
}
```

expected result:
```json
{
  "address":"1MdqwaSBy6rbasPJ9vmg2pZFJSVZ29GFpZ"
}
```

2023-11-07 21:00 UTC, roaminro requested changes

2023-11-08 02:00 UTC, gtandes commented on app/api/nicknames/[account]/address/route.ts
> +      const address = await getNicknameOwner(params.account)
done

2023-11-08 05:54 UTC, roaminro approved these changes

2023-11-08 05:54 UTC, merged