Get account history: for PR review
roaminro/koinos-rest pull request #21
Opened 2023-11-10 07:58 UTC by gtandes

2023-11-11 23:17 UTC, roaminro requested changes

2023-11-11 23:17 UTC, roaminro commented on app/api/account/[account]/history/route.ts
> +        address: params.account,
Cannot use `params.account` directly here, you should call `getAddress` on `params.account` before passing it to the call function. You can have look at other routes, most of them use `getAddress` ;)

2023-11-13 04:28 UTC, gtandes commented on app/api/account/[account]/history/route.ts
> +        address: params.account,
const account = await getAddress(params.account)

      const { values } = await provider.call<{
        values?: HistoryRecord[]
      }>('account_history.get_account_history', {
        address: account,
        limit,
        ascending,
        irreversible,
        decode_operations,
        decode_events,
        ...(seqNum && { seq_num: seqNum })
      })
      
      
      
  changes made

2023-11-13 05:24 UTC, roaminro approved these changes

2023-11-13 05:24 UTC, merged